export const tabs = [
  { label: '穿越火线', value: 'cf' },
  { label: '绝地求生', value: 'pubg' },
];

export const keyCodeOptions = [
  { label: 'Q', value: '16' },
  { label: 'W', value: '17' },
  { label: 'E', value: '18' },
  { label: 'R', value: '19' },
  { label: 'T', value: '20' },
  { label: 'Y', value: '21' },
  { label: 'U', value: '22' },
  { label: 'I', value: '23' },
  { label: 'O', value: '24' },
  { label: 'P', value: '25' },
  { label: 'A', value: '26' },
  { label: 'S', value: '27' },
  { label: 'D', value: '28' },
  { label: 'F', value: '29' },
  { label: 'G', value: '30' },
  { label: 'H', value: '31' },
  { label: 'J', value: '32' },
  { label: 'K', value: '33' },
  { label: 'L', value: '34' },
  { label: 'Z', value: '35' },
  { label: 'X', value: '36' },
  { label: 'C', value: '37' },
  { label: 'V', value: '38' },
  { label: 'B', value: '39' },
  { label: 'N', value: '40' },
  { label: 'M', value: '41' },
];
